### PR TITLE
Connected to CLINT data repo & added plotting

### PR DESCRIPTION
**Pull request by mmaiergerber**
## Additional Information

I was to fast and accidentally made my change in the main branch, but I immediately reverted it. Then I made the exact same change in the dev2 branch. This PR is now for you to review the changes. Thanks.

### CODE REVIEW

**Comment by mmaiergerber** [comment]
@cehbrecht This change in the code requires metview (software developed at ECMWF) to be installed for plotting purposes. May I ask you to install it for shearwater? Details can be found under: https://metview.readthedocs.io/en/latest/install.html
Many thanks!

**Comment by PaoloBonettiPolimi** [comment]
@cehbrecht I've tried to add the metview library requested by Michael in the environment.yaml and the requirement.txt, requirements_dev.txt as usual but I get some errors, I'll wait for you to double check it, and then I will go through the revision of the updates once the process is working.

**Comment by cehbrecht** [comment]
@PaoloBonettiPolimi @mmaiergerber tests are working now :) 

I switched to a "conda based build" in the tests. There was an issue with the `eccodes` ... maybe due to a missing env variable ... and conda might take care of it.

I have updated the `requirements_dev` ... we only need to add here the additional packages for testing.

I tried to get the linting fixed (pep8) and the docs build (lazy load metview). Please check it the code is still doing the right thing :)

The conda spec file is updated ... I will deploy it at the DKRZ VM.

**Review by cehbrecht — APPROVED** [review]

**Comment by cehbrecht** [comment]
@mmaiergerber I have deployed the dev2 branch ... but it fails with the following error:
```
Traceback (most recent call last):
  File "/usr/local/anaconda/envs/shearwater/lib/python3.11/site-packages/pywps/app/Process.py", line 260, in _run_process
    self.handler(wps_request, wps_response)  # the user must update the wps_response.
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/anaconda/envs/shearwater/lib/python3.11/site-packages/shearwater/processes/wps_cyclone.py", line 112, in _handler
    fs1_param = mv.read(
                ^^^^^^^^
  File "/usr/local/anaconda/envs/shearwater/lib/python3.11/site-packages/metview/bindings.py", line 1286, in wrapped
    return value_from_metview(val)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/anaconda/envs/shearwater/lib/python3.11/site-packages/metview/bindings.py", line 1240, in value_from_metview
    raise retval
Exception: Metview error: Error calling Metview function
```

I have rolled the installation back to main branch.

**Pull request closed without merging**
