### PR TITLE
first PR from dev to test of the prototype process implementation and related data

### PR DESCRIPTION
**Pull request by PaoloBonettiPolimi**
## Overview

This PR inserts the first prototype version in the main branch.

Changes:

* Added the process, some default data and the configurations needed to pass the tests. 

## Additional Information

Links to other issues or sources.

### CODE REVIEW

**Comment by cehbrecht** [comment]
@PaoloBonettiPolimi the CSV files in data are quite big like 100 MB. Would compression help?

**Comment by PaoloBonettiPolimi** [comment]
@cehbrecht I have changed the csv data to zip files. I have also changed the output to be ComplexOutput, with the link to the saved output file provided as output.

**Comment by cehbrecht** [comment]
@PaoloBonettiPolimi ... have added the `.DS_Store` files ... you could remove them and update the .gitignore.

**Comment by PaoloBonettiPolimi** [comment]
@cehbrecht done!

**Review by cehbrecht — APPROVED** [review]

**Pull request merged**
